# Generated by Django 3.2.4 on 2021-09-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210916_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaceinfo',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
